### ISSUE TITLE
Example of library use

### ISSUE THREAD

**Issue by EricCrosson** [emacsattic/map-progress#3]
Howdy tarsius,

Do you have an example handy of some code using this library? I find that much easier to get my project bootstrapped than guess and check.

Looks like a neat package, can't wait to give her a whirl.
Thanks!

**Comment by tarsius** [comment]
Ah sorry forgot about this.

There currently are no examples that you could look at, but it shouldn't be to hard to figure out. For example `mapc-with-progress-reporter` takes the same arguments as `mapc` (so see its doc-string). These arguments however are proceeded by the `msg` argument and followed by other optional arguments. These progress arguments are described in the doc-string of `make-progress-reporter`. Also see the [library header](https://github.com/tarsius/map-progress/blob/master/map-progress.el#L24).

**Comment by EricCrosson** [comment]
Thanks for the leads :)
